---
unclassified:
  metricsaccesskey:
    accessKeys:
      - key: "evergreen"
        description: "Key for evergreen health-check"
        canHealthCheck: true
        canPing: false
        canThreadDump: false
        canMetrics: false
        origins: "*"
