version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - 'POSTGRES_PASSWORD=grassisevergreener'
      # Used for psql non-interactive scripting
      - 'PGPASSWORD=grassisevergreener'
      - 'POSTGRES_DB=evergreen_development'
    ports:
      - '5432:5432'
    volumes:
      - ../services/initdb.d:/docker-entrypoint-initdb.d

  backend:
    image: jenkinsciinfra/evergreen-backend
    build: ../services
    environment:
      - 'DB_TRACING=1'
      - 'PGPASSWORD=grassisevergreener'
      - 'DB_CONNECTION_STRING=postgres://postgres:grassisevergreener@db:5432/evergreen_development'
    ports:
      - '3030:3030'
    depends_on:
      - db
    command: ['/wait-for-postgres.sh', "db", "5432", "/usr/local/bin/npm", "run", "start"]

  instance:
    image: jenkins/evergreen
    build: ./
    environment:
      - 'EVERGREEN_ENDPOINT=http://backend:3030'
      - 'LOG_LEVEL=debug'
      - 'INSECURE_SHOW_ADMIN_PASSWORD=true'
    ports:
      - '8080:8080'
      - '8081:8081'
      - '80:80'
    depends_on:
      - backend
    volumes:
      - ./client:/evergreen/client
