---
jenkins:
  clouds:
    - amazonEC2:
        cloudName: "ec2"
        instanceCapStr: 20
        # this shouldn't be needed, since without explicit creds this should
        # already be used but let's be explicit to avoid issues.
        useInstanceProfileForCredentials: true
        privateKey: "${PRIVATE_KEY}"
        templates:
          - description: "EC2 Agent"
            ami: "ami-cfe4b2b0"
            labelString: "agent"
            type: "T2Xlarge"
            securityGroups: "${AGENT_SECURITY_GROUP}"
            subnetId: "${AGENT_SUBNET}"
            remoteFS: "/home/ec2-user"
            remoteAdmin: "ec2-user"
            initScript: >
              sudo yum update -y;
              sudo yum remove -y java-1.7.0-openjdk ;
              sudo yum install -y docker java-1.8.0-openjdk-devel;
              sudo service docker start;
              sudo usermod -a -G docker ec2-user;
              sudo docker info;
